name 'ey-init'
maintainer 'Engine Yard'
maintainer_email 'support@engineyard.com'
version '1.0'
source_url 'https://engineyard.com'
issues_url 'https://support.engineyard.com'

depends 'ey-lib'
depends 'ey-core'
depends 'ey-base'
depends 'ey-custom'
