name 'node'
maintainer 'Engine Yard'
maintainer_email 'support@engineyard.com'
version '1.0'
source_url 'https://engineyard.com'
issues_url 'https://support.engineyard.com'

depends 'ey-lib'
depends 'god'
depends 'pm2'
