source 'https://rubygems.org/' do
  gem 'chef', '~> 12.7'
  gem 'right_aws', '~> 3.1.0'
  gem 'engineyard-serverside', '~> 2.6.6'
  gem 'ey_cloud_server', '1.4.51'
end

source 'https://nextgem.engineyard.com/' do
  gem 'ey_enzyme',              '2.0.5'
  gem 'ey_snaplock',            '2.0.3'
end
