name 'ey-core'
maintainer 'Engine Yard'
maintainer_email 'support@engineyard.com'
version '1.0'
source_url 'https://engineyard.com'
issues_url 'https://support.engineyard.com'

depends 'ey-lib'
depends 'ntp'
depends 'emerge'
depends 'ephemeraldisk'
depends 'ey-dynamic'
depends 'ey-instance-api'
depends 'ey-monitor'
depends 'lockrun'
depends 'logrotate'
depends 'openssl'
depends 'prechef'
depends 'security_updates'
depends 'sysctl'
depends 'sysklogd'
depends 'timezones'
