name 'util'
maintainer 'Engine Yard'
maintainer_email 'support@engineyard.com'
version '1.0'
source_url 'https://engineyard.com'
issues_url 'https://support.engineyard.com'

depends 'ey-lib'
depends 'deploy'
depends 'db_admin_tools'
depends 'deploy-keys'
depends 'ey-cron'
depends 'postgresql'
depends 'mysql'
depends 'ey-application'
depends 'app-logs'
depends 'memcached'
depends 'deploy'
depends 'lb'
